### ISSUE TITLE
Script closes due to this popup

### ISSUE THREAD

**Issue by UsmanNiazi** [CassiusVonthill/365datascience-scraper#2]
![image](https://user-images.githubusercontent.com/43772815/78891246-9dcbc080-7a80-11ea-86c3-f1f7ce27da60.png)

**Comment by CassiusVonthill** [comment]
EDIT: More questions and direct questions

I'm going to need some more information to properly debug this:
+ Did you just make this account?
+ Have you confirmed your email with this account?
+ Where in the process does this error happen (near the beginning when it logs you in or in the middle when it's going through the lessons)?

You can also use this maget while I check things out: magnet:?xt=urn:btih:a541e689910cb1a670e57b5f4d8929cf8acee665&dn=365datascience_v2

**Comment by UxmanKhan** [comment]
Yes. I have made my account.
I have confirmed my email 
i have tried creating a new mail as well as my own old mail that i'm personally using to take the course.
this pop up only comes up when i run the file & it logs in with the provided details. 
normal 365 datascience website through chrome does not ask that. 

PS: They have added a new course called "web scraping " . if you could also add that to the torrent, it'll be great. i have downloaded all the course from the torrent, just need that last one.

thanks

**Comment by UsmanNiazi** [comment]
Yes. I have made my account.
I have confirmed my email
i have tried creating a new mail as well as my own old mail that i'm personally using to take the course.
this pop up only comes up when i run the file & it logs in with the provided details.
normal 365 datascience website through chrome does not ask that.

PS: They have added a new course called "web scraping " . if you could also add that to the torrent, it'll be great. i have downloaded all the course from the torrent, just need that last one.

thanks
